[project]
name = "forge-mock"
version = "0.1.0"
description = "A synthetic data generator for Data Engineers using SQL DDL and statistical profiles."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Thomas Fynes", email = "tom@fynesforge.dev" }
]
keywords = ["data-engineering", "synthetic-data", "sql", "testing"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Database",
]
dependencies = [
    "typer>=0.12.0",
    "sqlglot>=23.0.0",
    "faker>=24.0.0",
    "polars>=0.20.0",
    "pyarrow>=15.0.0",
    "numpy>=1.26.0",
    "rich>=13.7.0",
    "sqlalchemy>=2.0.0",
    "pyyaml>=6.0.1",
    "tqdm>=4.67.3",
    "adbc-driver-sqlite>=1.11.0",
    "adbc-driver-postgresql>=1.11.0",
    "adbc-driver-manager>=1.11.0",
    "adbc-driver-flightsql>=1.11.0",
    "google-cloud-bigquery-storage>=2.37.0",
    "pandas>=3.0.2",
    "pyodbc>=5.3.0",
]

[project.optional-dependencies]
postgres = ["psycopg2-binary>=2.9.9"]
mysql = ["pymysql>=1.1.2"]
trino = ["trino[sqlalchemy]>=0.328.0"]
bigquery = ["sqlalchemy-bigquery>=1.9.0", "google-cloud-bigquery-storage>=2.24.0"]

[project.scripts]
forge-mock = "forge_mock.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "mypy>=1.9.0",
    "ruff>=0.3.0",
    "pytest-cov>=7.1.0",
    "types-pyyaml",
    "google-auth>=2.49.2",
    "google-cloud-bigquery>=3.41.0",
    "sqlalchemy-bigquery>=1.16.0",
]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# Ensure basic Python rules are checked
select = ["E", "F", "W"]

[tool.ruff.lint.per-file-ignores]
# F811: Redefinition of unused name. 
# We ignore this in tests because Pytest fixtures are often 
# seen as redefinitions by static linters.
"tests/*" = ["F811"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: marks tests as slow integration tests"
]
