"""forge.yaml writer — serialises a confirmed plan to a reusable config file."""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

import yaml


def write_forge_yaml(
    plan: dict[str, Any],
    output_path: str = "forge.yaml",
    connection_url: str = "",
) -> None:
    """Write a confirmed profile plan to a forge.yaml config file."""
    output = Path(output_path)

    config: dict[str, Any] = {
        "_forge_mock": {
            "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "version": "1",
        },
        "tables": plan.get("tables", {}),
    }

    if connection_url:
        from forge_mock.connectors.sqlalchemy_connector import _mask_url

        config["_forge_mock"]["source_database"] = _mask_url(connection_url)

    with output.open("w", encoding="utf-8") as fh:
        fh.write("# forge-mock configuration\n")
        fh.write(f"# Generated by `forge-mock plan` at {config['_forge_mock']['generated_at']}\n")
        fh.write("# Run with: forge-mock generate schema.sql --config forge.yaml\n")
        fh.write("#        or: forge-mock connect $DATABASE_URL --config forge.yaml\n\n")
        yaml.dump(config, fh, default_flow_style=False, sort_keys=False, allow_unicode=True)


def load_forge_yaml(path: str = "forge.yaml") -> dict[str, Any]:
    """Load an existing forge.yaml, stripping internal metadata keys."""
    p = Path(path)
    if not p.exists():
        return {}
    with p.open("r", encoding="utf-8") as fh:
        raw: dict[str, Any] = yaml.safe_load(fh) or {}
    raw.pop("_forge_mock", None)
    return raw
